apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: docker-swarm-visualizer
  name: docker-swarm-visualizer
spec:
  selector:
    matchLabels:
      app: docker-swarm-visualizer
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: docker-swarm-visualizer
        ssd.admissionreview.accountname: dev
        ssd.admissionreview.appname: docker-swarm-dev
    spec:
      nodeSelector:
        application: spinnaker
      containers:
      - name: docker-swarm-visualizer
        image: quay.io/opsmxpublic/docker-swarm:8a93f07-401
